<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE grid [
  <!ENTITY FilterCheckAccessUnit "(@@admin = 1 or exists(select 1 from sysunitrights r where r.user_id = @@userID and r.ma_dvcs = @@table.ma_dvcs and r.r_access=1))">
  <!ENTITY DowloadScript SYSTEM "..\Include\Javascript\DownloadScript.txt">
  <!ENTITY TransferID "DeclarationItemAutoGenerated">
  
  <!ENTITY CreateTicket "FastBusiness.Encryption.Begin$sp4+hMHegg2EZffLn/pV+7CT0erm8Pelc62zDbCP7bi82XzHNctnfZNnq4DaUT2uAl/q4frx8ucAGmzklj1xzZDSpAyjpeWXHC6FP7o8H3hOgMTieyQSl27334FRqJ+NkNaUT2oUS8KAu+PRxD3G2V6EU7MZpwxrcUJ7IHg0yVbis6AH6Zo6UNpSN6dmpKUwGujH8lwF2cLiKGLGyEqJKzULzp2kMqPGg5BQ/OafhxkU/1Sm4OUjo2rYi52E0lgIAA1bY2FL7mjmvoig50fuQ3SzFyPY3r88IktAFcXhuJHAkHdGn7Q9FNbQwOMPB3VSilmHYNZfigee89RI5bQve/a6+6TY+OlXntPtUoAdWb5kqFdzCmP1eQgrg+51y15bhFn/SQdzoLUJ77CgU1pA+A==FastBusiness.Encryption.End&TransferID;FastBusiness.Encryption.Begin$zUIvsNhGh4/9Y3Ut8bNJFAkX2zzhxNgY5Mi7p+EBoJzdY1foFs8S+2hNeJQliUjhMyXucck61QV8R3CeK2qq3tDa2nM+4JWI5eJfjM/y3YE=FastBusiness.Encryption.End">
  
]>

<grid table="vdmvtxktd" code="ma_dvcs, ma_vt" filter="&FilterCheckAccessUnit;" order="ma_dvcs, ma_vt" xmlns="urn:schemas-fast-com:data-grid">
  <title v="Khai báo vật tư xuất kho tự động" e="Declaration Item for Auto-Generated Issue"></title>
  <subTitle v="Loại vật tư: %s..." e="Item Type: %s..."></subTitle>

  <fields>
    <field name="ma_dvcs" isPrimaryKey="true" width="100" allowFilter="true" allowSorting="true">
      <header v="Đơn vị" e="Unit"></header>
    </field>
    <field name="ma_vt" isPrimaryKey="true" width="100" allowFilter="true" allowSorting="true">
      <header v="Mã vật tư" e="Item"></header>
    </field>
    <field name="ten_vt%l" width="300" allowFilter="true" allowSorting="true">
      <header v="Tên vật tư" e="Item Name"></header>
    </field>
  </fields>

  <views>
    <view id="Grid">
      <field name="ma_dvcs"/>
      <field name="ma_vt"/>
      <field name="ten_vt%l"/>
    </view>
  </views>
  <commands>
    <command event="Loading">
      <text>
        &CreateTicket;
        <![CDATA[<Encrypted>&mESLYKUGR/20AFH6ZrQMu3FpC9Jock0vSy2vnVGePvl04AQbI7kzeDkVHKYYxt6ibMbgBKX+0XSN0QTXpyMAdpCBOrXc7tBA0FETyg/t6ghjP1Y8g+UlhsLjlObvBuXORFG8odd5gVk3f9ed8QU8EuXulDdMuQikvhFbODep0pRpJvhACvzMkpknuNXrBplJCHrAQVgZzmPRv8PQLMTE1KDQIG4MhqMU33deeUhkKREJvspUdATndd5+G0zTRnvs34ok8er4KZH0UPoZTyJuecfR0mhWdutrLWaYvU2PBglng+0BQ64vhq0TZsdIk6ZobW8q/at+KFlgf5IDDbfWbFaq+YajsV2FTPzeaJOuoTHcWILASjRXOn5OGe7gQV4wuRTsCw8lYq3bEurCL25fvW/OOTQC4Q2vxbLfW5SpZGmnSLrQ5KHu9uSiXwy+W6LfN5A1j2hvaP4iix5JTOoL3YMlxwtdL4QZKubNnHLD02WM6UQI/X/ivpfOAXHAUCbk</Encrypted>]]>
      </text>
    </command>

    <command event="Closing">
      <text>
        <![CDATA[<Encrypted>&JFAg3c674j2f8bRB56rmcI1OfO5PPwycxsiU4myOMGMXvKkw+sfpfPbFvee6tiiV29Q2/yLFmghXIFXg4V0kpP2TZ2wjHsrVkonMK4JODzzw9LEFow/y0d3we19NN0DC</Encrypted>]]>
      </text>
    </command>

  </commands>
  <script>
    <text>
      <![CDATA[<Encrypted>&urCjYVIWi8oLG4/CqhNJtWehdgJi0Vk6qESNFVjeZPwicmJ0tYu79nIEs5+hPdTFWmOO+cKaAxbP59A0AaU7+eoFcnILlIF/XzlhYpOAduAq5i9Ofc9tKNetKSmfL+6fq1AEaK46QkRsJMDMqvEoSRaWQtL2uIyvXkc5TkGrV++qLgHkhK4NUzR6d8g1PuyECJDdW3q0tfVUDNQcIS6E9vxInVEB62lkcmoKS8ujp0q2Q1+A6fwHah+RZP1FxoFzEUVv3EoIVk33M4T+vKLhS1TC3krWAznKhUpUBV5na9nRSvBywFLkXEWcw5eIGxXitgur+KE8dIIaIsciSeQKobUMB3PbIoWbPplepvVVe7byPd/pFqglrQMYSP29rroJzNP6SCpX9xZ+0B43/rRdeqJKZ0UGdqXDP2mrvf2JXXaOJpjfbyK70NhwbahPHxGG8rIsdg6mWbuFvtDOX3tHKDLdqbbF/o5e6x7MkfTPIc9E2B+cep/nxrfjpND62jXadG9KQ5CpSrSawhKKSS4FQjtWB+v2I13XhwqeLIfYlVvM+DSILDHyiUwRG34kjVx2</Encrypted>]]>
      &DowloadScript;
    </text>
  </script>

  <css>
    <text>
      <![CDATA[<Encrypted>&mESLYKUGR/20AFH6ZrQMu7Q2ZgN87qIJvPvG6Hzq8L9loaCflvmvkNH8VLZ2CkRZovJCEiJ6AR3gqMbkiE31/Oc3ZzMUpRFDqWVExQBJV+Zr88IlDe/oSzZRA1t8b0/0w3BqTKi7PnWnO02iO/Cwi4Gr5JH1yfJJpAAx17dZWFyA05PJJcj/N8dU0K9UVDsl</Encrypted>]]>
    </text>
  </css>

  <response>
    <action id="Download">
      <text>
        &CreateTicket;<![CDATA[<Encrypted>&JFAg3c674j2f8bRB56rmcAwBgUhlM+p12yj1evxkfcDUP9CeRQRDt/OIcHdxnMr2oXPo5oho2Ss1hSl27MFMjg==</Encrypted>]]>
      </text>
    </action>
  </response>

  <toolbar>
    <button command="New">
      <title v="Toolbar.New" e="Toolbar.New"></title>
    </button>
    <button command="Edit">
      <title v="Toolbar.Edit" e="Toolbar.Edit"></title>
    </button>
    <button command="Delete">
      <title v="Toolbar.Delete" e="Toolbar.Delete"></title>
    </button>
    <button command="Search">
      <title v="Toolbar.Search" e="Toolbar.Search"></title>
    </button>
    <button command="View">
      <title v="Toolbar.View" e="Toolbar.View"></title>
    </button>
    <button command="-">
      <title v="-" e="-"/>
    </button>
    <button command="ImportData">
      <title v="Lấy dữ liệu từ tệp..." e="Import Data from File..."></title>
    </button>
    <button command="Download">
      <title v="Tải tệp mẫu..." e="Download Template File..."/>
    </button>
    <button command="Seprate">
      <title v="-" e="-"></title>
    </button>
    <button command="Freeze">
      <title v="Toolbar.Freeze" e="Toolbar.Freeze"></title>
    </button>
  </toolbar>
</grid>